version: 2
updates:
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "daily"  # daily, weekly, monthlyから選べる
    # オプション設定

    labels:
      - "dependencies"
      - "submodules"
