baseurl = "https://hugo.kto.f5.si"
DefaultContentLanguage = "ja"
title = "汐Official"
# Using theme as git submodule
theme = "material"
# Or when using theme as hugo module
# theme = "github.com/halogenica/beautifulhugo"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"

[markup.highlight]
  codeFences = false
  noClasses = false

[Services]
  [Services.Disqus]
    # Shortname = "XXX"
  [Services.googleAnalytics]
    # id = "XXX"


[[menu.main]]
  name = "Tags"
  url = "/tags/"
  weight = 1
  [menu.main.params]
    icon = "label"

[[menu.main]]
  name = "About"
  url = "/page/about/"
  weight = 2
  [menu.main.params]
    icon = "info"
