name: 🔄Update Submodules
on:
  push:
    branches: ["main"]

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v6
        with:
          submodules: recursive
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: 🔐 Configure git
        run: |
          echo "⚙️ Let's set up your Git user settings..."
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          echo "✅ Settings complete!"

      - name: 🔄 Update submodules
        id: update_step
        run: |
          echo "🚀 Checking submodules are up to date..."
          # Check the specified branch for each submodule
          git submodule foreach '
            BRANCH=$(git config -f $toplevel/.gitmodules submodule.$name.branch || echo main)
            echo "📂 $name branch: Getting $BRANCH..."
            git fetch origin $BRANCH
            git checkout $BRANCH
            git pull origin $BRANCH
          '
          git add .
          echo "✨ Submodule update process is complete!"
          
      - name: 👀 Check for changes
        id: check
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            echo "changed=true" >> $GITHUB_OUTPUT
            echo "🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥"
            echo "📢 Found an update!"
            echo "🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥"
          else
            echo "changed=false" >> $GITHUB_OUTPUT
            echo "✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨"
            echo "😴 No changes. Everything is up to date!"
            echo "✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨✨"
          fi
          
      - name: ➕ Create or Update Pull Request
        if: steps.check.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v8
        with:
          # By using a fixed name, you can overwrite old branches without increasing them.
          branch: auto-update/submodules
          delete-branch: true
          commit-message: "🤖chore: update submodules"
          title: "🤖Update submodules"
          body: |
            ## 🔄 Automatic submodule updates
            I found a new update and created (or updated) a PR!
          labels: dependencies, submodules

      - name: 🏁 Final Summary
        run: |
          if [[ "${{ steps.check.outputs.changed }}" == "true" ]]; then
            echo "🎉 Work done! Check out the pull request on GitHub."
          else
            echo "🌈 No need to do anything! That's it for today. Good job!"
          fi
