name: 🔄Update Submodules
on:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: 🔐Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: 🎲Generate random ID
        id: random
        run: |
          # A-Z, a-zからランダムに5文字抽出
          ID=$(tr -dc 'A-Za-z' < /dev/urandom | head -c 5)
          echo "id=$ID" >> $GITHUB_OUTPUT
      
      - name: 🔄Update submodules
        run: |
          git submodule foreach 'git fetch origin && git checkout $(git config -f $toplevel/.gitmodules submodule.$name.branch || echo main) && git pull origin $(git config -f $toplevel/.gitmodules submodule.$name.branch || echo main)'
          git add .
          
      - name: 👀Check for changes
        id: check
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          fi
          
      - name: ➕Create Pull Request
        if: steps.check.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v8
        with:
          # ここで生成したIDを末尾に付与
          commit-message: "🤖chore: update submodules ${{ steps.random.outputs.id }}"
          # ブランチ名にもIDを入れると、古いプルリクと競合しなくなるよ
          branch: update-submodules
          title: "🤖Update submodules ${{ steps.random.outputs.id }}"
          labels: dependencies, submodules
